import json
M=['Oct 26','Nov 26','Dec 26','Jan 27','Feb 27','Mar 27','Apr 27','May 27','Jun 27']
# (group, role, seniority, loading per month Oct..Jun, primary skills, tools/secondary)
R=[
('mgmt','Delivery Manager / TPM','Senior (12+ yrs)',[1,1,1,1,1,1,1,1,0.25],
 'Hybrid agile delivery of multi-squad programmes; integrated planning, critical-path and dependency management; RAID; stakeholder and steering management; change control; release governance',
 'JIRA / Trello, MS Project or equivalent, Confluence-style wiki'),
('mgmt','Scrum Master','Mid–Senior (6+ yrs)',[0,1,1,1,1,1,1,0.5,0],
 'Scrum facilitation across 4 squads; sprint metrics (velocity, burndown, predictability); impediment removal; scrum-of-scrums',
 'JIRA / Trello boards and reports'),
('mgmt','Solution Architect (.NET / PostgreSQL)','Senior (12+ yrs)',[1,1,1,1,1,1,0.75,0.5,0],
 'ASP.NET Core modular-monolith and domain-driven design; PostgreSQL data architecture; OAuth2 / OIDC identity design; event-driven integration (transactional outbox, message brokers); payment-gateway architecture incl. Razorpay Route split settlement; React Native client architecture; OWASP ASVS; DPDP-aligned data design',
 'C4 / architecture diagrams, ADRs, SportSeek cloud platform services'),
('design','Business Analyst','Mid–Senior (6+ yrs)',[2,2,2,2,1.5,1.5,1,0.5,0],
 'Requirement workshops; user stories with Given/When/Then acceptance criteria; booking, events, payments/refunds and partner-onboarding domains; process and state modelling; SOW traceability; UAT scenario design',
 'JIRA / Trello, BPMN / flow diagrams'),
('design','UX / UI Designer','Mid–Senior (5+ yrs)',[1.5,2,2,2,1,1,0.5,0,0],
 'Atomic design systems (tokens → atoms → templates); mobile (iOS/Android) and responsive web UI; usability research and testing; accessibility (WCAG 2.1 AA); prototyping; developer hand-off',
 'Figma or tool agreed with SportSeek'),
('backend','.NET Tech Lead','Senior (10+ yrs)',[1,2,2,2,2,2,1,1,0],
 'C# / ASP.NET Core Web API; EF Core with Npgsql; modular boundaries and architecture tests; OIDC server/client implementation (e.g. OpenIddict or ASP.NET Core Identity); background jobs and scheduling; idempotency and webhook handling; code review and mentoring',
 'xUnit, Testcontainers for .NET, NetArchTest / ArchUnitNET, OpenAPI tooling'),
('backend','.NET Backend Engineer','Mid (4–8 yrs)',[2,4,4,4,4,3,2,1,0],
 'C# / ASP.NET Core; EF Core + Npgsql; LINQ and SQL; REST APIs with OpenAPI; integration with Razorpay (payments, refunds, Route, webhooks), SMS, WhatsApp BSP, FCM/APNs and email; messaging consumers; unit and integration testing',
 'xUnit, Testcontainers, Postman'),
('backend','PostgreSQL Database Engineer','Senior (8+ yrs)',[0.5,0.5,1,1,0.5,0.5,0.5,0.25,0],
 'Schema-per-domain design; EF Core migrations with expand/contract; JSONB with schema validation; exclusion constraints (btree_gist) for double-booking prevention; geospatial radius queries; indexing and query tuning (EXPLAIN ANALYZE); backup / point-in-time recovery; identity de-duplication and data-migration scripts; reconciliation SQL',
 'psql, pg_stat_statements, PostGIS where used'),
('mobile','React Native Lead','Senior (8+ yrs)',[1,1,1,1,1,1,0.5,0.5,0],
 'React Native with TypeScript for iOS and Android; navigation, state and API layers; native modules; OIDC with PKCE on mobile (e.g. react-native-app-auth); push notifications (FCM/APNs, e.g. React Native Firebase); deep links / universal links and app-switch handling; minimum-version enforcement; store release management',
 'Fastlane, Xcode, Android Studio, crash and performance monitoring'),
('mobile','React Native Engineer','Mid (4–7 yrs)',[1,1,2,2,2,1,1,0.5,0],
 'React Native + TypeScript; REST integration; schema-driven dynamic forms (partner onboarding); offline/error states; accessibility; unit and component testing; device/OS compatibility fixes',
 'Jest, React Native Testing Library, Detox or Maestro'),
('web','Web Front-end Lead (React)','Senior (8+ yrs)',[0,0.5,1,1,1,1,1,0.5,0],
 'React + TypeScript; Next.js server rendering for SEO-relevant public pages; shared design tokens / component library with the React Native apps; OIDC for web clients; performance (Core Web Vitals); WCAG 2.1 AA',
 'Next.js, Storybook, Playwright'),
('web','Web Front-end Engineer (React)','Mid (3–6 yrs)',[0,0,2,2,2,2,1,0.5,0],
 'React + TypeScript; responsive layouts; forms and validation; API integration; admin and partner web screens incl. ledger tables, filters, sorting and exports',
 'Next.js, Playwright, Jest'),
('qa','QA Lead (Automation)','Senior (8+ yrs)',[1,1,1,1,1,1,1,1,0.25],
 'Test strategy and quality gates; automation architecture for API, React Native and web; CI integration; SIT and regression planning; defect governance; UAT support',
 'Playwright, Detox / Maestro / Appium, Postman / Newman, xUnit'),
('qa','QA Engineer','Mid (3–6 yrs)',[1.5,1,2,2,2,2,2,1,0],
 'Functional and regression testing on iOS, Android and web; API testing; payment, refund, waitlist and notification test scenarios using Razorpay test mode; test-data management; automated test authoring',
 'Postman, Playwright, device farm / physical devices'),
('ops','DevOps / SRE Engineer','Senior (7+ yrs)',[1,1.5,1,1,1,1,1,1,0.5],
 'Infrastructure as code in SportSeek\'s cloud; CI/CD for .NET services and React Native builds; managed PostgreSQL operations; containers; observability (OpenTelemetry for .NET, logs, metrics, alerting); secrets management; backup/restore drills; release automation and on-call',
 'Terraform or cloud-native IaC, SportSeek\'s CI platform, Fastlane'),
('spec','Security Engineer (VAPT)','Senior (8+ yrs)',[0.5,0.25,0,0.25,0.25,0.25,0.5,0.25,0],
 'Web, API and mobile penetration testing (OWASP WSTG, MASTG); SAST/DAST/SCA tool set-up and triage; secure .NET and React Native review; remediation verification',
 'SAST / DAST / SCA tooling, Burp Suite or equivalent'),
('spec','Performance Engineer','Mid–Senior (6+ yrs)',[0.5,0,0,0.25,0.25,0.25,0.5,0,0],
 'Load and stress test design; .NET API profiling; PostgreSQL query and connection-pool analysis; capacity recommendations',
 'k6 or JMeter, dotnet-counters / dotnet-trace'),
]
G={'mgmt':'Programme & architecture','design':'Analysis & UX','backend':'.NET & PostgreSQL','mobile':'React Native','web':'React web','qa':'Quality engineering','ops':'DevOps / SRE','spec':'Specialists'}
tot=[round(sum(r[3][i] for r in R),2) for i in range(len(M))]
pm=round(sum(tot),2)
json.dump(dict(months=M,roles=[dict(group=g,role=n,seniority=s,load=l,skills=k,tools=t,pm=round(sum(l),2),peak=max(l)) for g,n,s,l,k,t in R],groups=G,total=tot,pm=pm),open('res.json','w'),indent=1)
print(tot,pm)
